### ISSUE TITLE
Segmentation fault on saving new map from the map editor

### ISSUE THREAD

**Issue by simon-v** [sirjuddington/SLADE#1136]
**SLADE Version**: git 86a03058, compiled from AUR
**Operating System**: Arch Linux

**Issue Details**:
1) Create a new map;
2) Add a sector;
3) Click "Save";

At this point SLADE freezes; The last line in the terminal says `Caught unhandled unknown exception; terminating`

Using gdb, the following backtrace was acquired:
```Thread 1 "slade" received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff5dffcb0 in  () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff5e03ab9 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff5e056b0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff6675392 in  () at /usr/lib/libgtk-3.so.0
#4  0x00007ffff5e172aa in g_object_run_dispose () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff7621117 in wxMenu::~wxMenu() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#6  0x00007ffff762116a in wxMenu::~wxMenu() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#7  0x00007ffff7728857 in wxMenuBarBase::~wxMenuBarBase() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#8  0x00007ffff7620dca in wxMenuBar::~wxMenuBar() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#9  0x00007ffff76c1056 in wxFrameBase::DeleteAllBars() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#10 0x00007ffff7615af1 in wxFrame::~wxFrame() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#11 0x0000555556407262 in STopWindow::~STopWindow() (this=0x555557acd5a0, __in_chrg=<optimized out>)
    at /usr/include/c++/9.3.0/ext/new_allocator.h:89
#12 0x0000555555d9bc19 in MainWindow::~MainWindow() (this=0x555557acd5a0, __in_chrg=<optimized out>)
    at ./slade/src/MainEditor/UI/MainWindow.cpp:130
#13 0x00007ffff7656eb6 in wxAppBase::CleanUp() () at /usr/lib/libwx_gtk3u_core-3.0.so.0
#14 0x00007ffff7143fbf in wxEntryCleanup() () at /usr/lib/libwx_baseu-3.0.so.0
#15 0x00007ffff714404e in wxUninitialize() () at /usr/lib/libwx_baseu-3.0.so.0
#16 0x00007ffff71454dc in wxEntry(int&, wchar_t**) () at /usr/lib/libwx_baseu-3.0.so.0
#17 0x0000555555a7a053 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at ./slade/src/Application/SLADEWxApp.cpp:454```

No freeze occurs when saving an empty map, or an existing map to which changes were made.

**Comment by simon-v** [comment]
Rebuilt today at 3df082ca6bc835165c1495c829a4aaa12be2e1d6 and the crash no longer occurs. Don't know what you did, but it worked. Thanks for all the hard work!
