### ISSUE TITLE
Linux Mint 21.1 (Ubuntu 22.04): Startup crash

### ISSUE THREAD

**Issue by Wohlstand** [sirjuddington/SLADE#1538]
**SLADE Version**: 472df3113d536a495b7daf574d4ee0744f7827e7
**Operating System**: Linux

**Issue Details**:
Note: I made a clear build from the scratch running `cmake -DCMAKE_BUILD_TYPE=Release ..`, then `make -j 16` (at me is Intel Core i7-11700KF CPU).

The SLADE doesn't starts at all and crashes on startup, there is a GDB output I got:
```
/build$ gdb ./slade 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./slade...
(No debugging symbols found in ./slade)
(gdb) run
Starting program: /home/vitaly/_git_repos_other/SLADE/build/slade 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9b1e640 (LWP 104675)]
[New Thread 0x7fffe931d640 (LWP 104676)]
[New Thread 0x7fffe8aa9640 (LWP 104677)]
[New Thread 0x7fffdbfff640 (LWP 104678)]
[New Thread 0x7fffdb7fe640 (LWP 104679)]
[Thread 0x7fffdb7fe640 (LWP 104679) exited]

Thread 1 "slade" received signal SIGSEGV, Segmentation fault.
0x0000555555d0feef in slade::icons::iconDef(slade::icons::Type, std::basic_string_view<char, std::char_traits<char> >) ()
(gdb) bt
#0  0x0000555555d0feef in slade::icons::iconDef(slade::icons::Type, std::basic_string_view<char, std::char_traits<char> >) ()
#1  0x0000555555d1375e in slade::icons::getIcon(slade::icons::Type, std::basic_string_view<char, std::char_traits<char> >, int, slade::Vec2<int>) ()
#2  0x0000555555dfd509 in slade::MainWindow::setupLayout() ()
#3  0x0000555555e00326 in slade::MainWindow::MainWindow() ()
#4  0x0000555555d74e50 in slade::maineditor::init() ()
#5  0x0000555555b801f0 in slade::app::init(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, double) ()
#6  0x0000555555b8c0bf in SLADEWxApp::OnInit() ()
#7  0x00007ffff70e2bd2 in wxEntry(int&, wchar_t**) () at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#8  0x0000555555af2d6c in main ()
```

**Comment by sirjuddington** [comment]
This one looks like you don't have the correct data in slade.pk3 or the dist/res directory. Looking at that log you're running it from a 'build' directory, try copying the executable to dist so it can find the right resources
