### ISSUE TITLE
Archive crash on exit

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#417]
Not sure exactly what caused this.  I had one PK3 archive open, and the map editor open and modified.  I quit SLADE from the main window, said I don't want to save the map, and got this crash:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000008188a8 in ArchiveTreeNode::getArchive (this=0x7400000061) at /home/eevee/dev-foreign/slade.git/src/Archive.cpp:114
114             if (parent)
(gdb) bt
#0  0x00000000008188a8 in ArchiveTreeNode::getArchive (this=0x7400000061) at /home/eevee/dev-foreign/slade.git/src/Archive.cpp:114
#1  0x00000000008188c1 in ArchiveTreeNode::getArchive (this=0x1f2f650) at /home/eevee/dev-foreign/slade.git/src/Archive.cpp:115
#2  0x0000000000b9fc09 in ArchiveEntry::getParent (this=0x35e5610) at /home/eevee/dev-foreign/slade.git/src/ArchiveEntry.cpp:130
#3  0x0000000000ba0736 in ArchiveEntry::stateChanged (this=0x35e5610) at /home/eevee/dev-foreign/slade.git/src/ArchiveEntry.cpp:547
#4  0x0000000000b9ff83 in ArchiveEntry::unlock (this=0x35e5610) at /home/eevee/dev-foreign/slade.git/src/ArchiveEntry.cpp:258
#5  0x00000000007e90dc in MapEditorWindow::lockMapEntries (this=0x3601ad0, lock=false) at /home/eevee/dev-foreign/slade.git/src/MapEditorWindow.cpp:462
#6  0x00000000007ecc3f in MapEditorWindow::closeMap (this=0x3601ad0) at /home/eevee/dev-foreign/slade.git/src/MapEditorWindow.cpp:928
#7  0x00000000007ee444 in MapEditorWindow::onClose (this=0x3601ad0, e=...) at /home/eevee/dev-foreign/slade.git/src/MapEditorWindow.cpp:1286
#8  0x00007ffff483c43e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#9  0x00007ffff49c2a77 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#10 0x00007ffff49c2e5e in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#11 0x00007ffff49c2eee in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#12 0x00007ffff49c2d23 in wxEvtHandler::DoTryChain(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#13 0x00007ffff49c3015 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#14 0x00007ffff49c2d77 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#15 0x00007ffff555d677 in wxWindowBase::Close(bool) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#16 0x0000000000a65057 in MapEditorWindow::deleteInstance () at /home/eevee/dev-foreign/slade.git/src/MapEditorWindow.h:59
#17 0x0000000000a60781 in MainApp::OnExit (this=0x1558a00) at /home/eevee/dev-foreign/slade.git/src/MainApp.cpp:1024
#18 0x00007ffff48d01ef in wxEntry(int&, wchar_t**) () from /usr/lib/libwx_baseu-3.0.so.0
#19 0x0000000000a47cee in main (argc=3, argv=0x7fffffffdd18) at /home/eevee/dev-foreign/slade.git/src/MainApp.cpp:417
(gdb) p parent
Cannot access memory at address 0x7400000081
```

I might not even have noticed if I hadn't been running under gdb for other reasons.

**Comment by sirjuddington** [comment]
Closing - old issue, possibly fixed by now

Feel free to reopen the issue if needed
