### ISSUE TITLE
Arbitrarily crashing during normal use

### ISSUE THREAD

**Issue by OrdinaryMagician** [sirjuddington/SLADE#859]
**SLADE Version**: afc8d3a
**Operating System**: Linux

**Issue Details**:
Since the latest commit SLADE has a tendency to randomly crash while I'm doing any sort of operation, be it opening a file, editing some script, viewing sprites, exporting lumps... anything, really. It's getting on my nerves as I'm trying to get some work done and I have to constantly spam save to not lose too much time on this (but even then it can also crash while saving).

**Comment by sirjuddington** [comment]
So it stops when you go back to a previous commit? Do you get any stack traces?

**Comment by OrdinaryMagician** [comment]
I haven't been able to reproduce it after building with debug info yet, but I'll post a stack trace once I do.

**Comment by OrdinaryMagician** [comment]
Well that's not very helpful looking...
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
slade: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

Thread 1 "slade" received signal SIGABRT, Aborted.
0x00007ffff2119860 in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff2119860 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff211aec9 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff21120bc in __assert_fail_base () at /usr/lib/libc.so.6
#3  0x00007ffff2112133 in  () at /usr/lib/libc.so.6
#4  0x00007ffff18dec3a in  () at /usr/lib/libX11.so.6
#5  0x00007ffff18deceb in  () at /usr/lib/libX11.so.6
#6  0x00007ffff18defdd in _XEventsQueued () at /usr/lib/libX11.so.6
#7  0x00007ffff18d0ca7 in XPending () at /usr/lib/libX11.so.6
#8  0x00007ffff1e87d27 in  () at /usr/lib/libgdk-x11-2.0.so.0
#9  0x00007ffff15d29fa in g_main_context_check () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff15d2f96 in  () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff15d33b2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff3619df3 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007ffff5f4ca36 in wxGUIEventLoop::DoRun() ()
    at /usr/lib/libwx_gtk2u_core-3.0.so.0
#14 0x00007ffff56bae84 in wxEventLoopBase::Run() ()
    at /usr/lib/libwx_baseu-3.0.so.0
#15 0x00007ffff567e537 in wxAppConsoleBase::MainLoop() ()
    at /usr/lib/libwx_baseu-3.0.so.0
#16 0x00007ffff570f308 in wxEntry(int&, wchar_t**) ()
    at /usr/lib/libwx_baseu-3.0.so.0
#17 0x00005555558557b8 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
```

**Comment by aFoxNamedMorris** [comment]
Happening on Linux here, as well.  Built using latest source.

**Comment by OrdinaryMagician** [comment]
So, I don't know if this is because of all the refactoring going on but the random crashing seems to no longer happen.

**Comment by sirjuddington** [comment]
Ok that's good then, probably something to do with that yeah (I'd generally recommend sticking with the stable branch at the moment)
